version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      #- WATCHTOWER_MONITOR_ONLY=true
      - TZ=${TIMEZONE}
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_DISCORD_WEBHOOK}
      # By default - do not update any container. Only update containers explicitely enabled with:
      # LABEL com.centurylinklabs.watchtower.enable="true"
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
